### ISSUE TITLE
[QST] Why using 2MB/4MB msg size data in benchmark to demostrate the performance in transimitting ~4K camera images?

### ISSUE THREAD

**Issue by ZhenshengLee** [osrf/TSC-RMW-Reports#105]
Hi,

This report espeacially the response from dds vendors is really valuable. And I have a question about the benchmark for 4K camera images transport performance.

Typically, the 4K image is with 8M pixels and the data size is (24/8) * 3840 * 2160 bytes or about 24.9MB

So, the msg data size shouble be around 25MB, am I right?

Or, is there a strong need for compression for image transimition?

Thanks.

**Comment by clalancette** [comment]
> Typically, the 4K image is with 8M pixels and the data size is (24/8) * 3840 * 2160 bytes or about 24.9MB

That's right, for 24bpp.  If you are using 8bpp, then it would be about 8MB.

Regardless, the response from the vendors is where they selected the sizes (2MB from eProsima Fast-DDS, 4MB for Eclipse CycloneDDS).  I'm not sure why they chose those sizes; it would be good to ask them.

> Or, is there a strong need for compression for image transimition?

Generally, that is going to be true.  Sending an uncompressed 4K 24bpp stream at 30Hz is going to take ~711MB/s on the network, so basically saturating a gigabit link.

With all of that said, I'm going to close this one out.
